### ISSUE TITLE
auto trade ?

### ISSUE THREAD

**Issue by onthetunnel** [jsappme/node-binance-trader#1]
hello,  can i know this project can do auto trade or not , because i has runs three days , no one order on my binance acc ...hope you can help , Thanks You!

**Comment by jsappme** [comment]
Hi, I am going to publish a new version of this old script in a few minutes. Feel free to open more issues after.
HF.

**Comment by onthetunnel** [comment]
Thanks for reply ! and hope it can open trade now ...if this project can do triangular arbitrage + TA strategy trading is awesome ! And many Thanks for your amazing  bot ! Thanks!

**Comment by jsappme** [comment]
I released the new version of this node binance trader, I am closing this issue for now because I completely rewrote the repo. feel free to open a new issue if you encounter problems. Thanks.

Have a great day.
