### ISSUE TITLE
Sponsor username invalid

### ISSUE THREAD

**Issue by dargmuesli** [jsappme/node-binance-trader#110]
The sponsor button of this GitHub repository shows that the user "jsappme" hasn't applied to sponsoring yet. I'd propose to do so or remove the `FUNDING.yml`.

**Comment by jsappme** [comment]
My sponsor application is still pending.

**Comment by dargmuesli** [comment]
I've temporarily disabled the funding button by renaming the funding configuration until the application is approved. This way we don't confuse users.
