### ISSUE TITLE
Support for usdt instead of btc

### ISSUE THREAD

**Issue by Bagz966** [jsappme/node-binance-trader#115]
Looking into option to switch between using USDT for trading instead of BTC if needed to override buy/sell signal. this way we can still use strats that use btc as a holder.

**Comment by dargmuesli** [comment]
That's already possible on the [testing branch](https://github.com/jsappme/node-binance-trader/tree/testing). Server side support will be included in the next backend released. Scheduled to happen in the next weeks, @jsappme said.
