### ISSUE TITLE
nbt  will stop request binance after serveral minutes

### ISSUE THREAD

**Issue by godisrko** [jsappme/node-binance-trader#12]
BUYING 6.79300000 OF ONT AT MARKET PRICE
⠋  ⚠️  Press [ CTRL + c ] or q to cancel the trade and sell everything at market price. ⚠️ 
 
⠴  2:40:46   ONTUSDT          qty:15.189 @ 4.41900000     pnl:0.000 INITAL BUY ORDER FULLY EXECUTED 
⠇  2:40:46   ONTUSDT          qty:15.189 @ 4.41900000     pnl:0.000 FINAL BUY PRICE @ 4.419
⠙  2:40:47   ONTUSDT          qty:29.318 @ 4.41900000     pnl:0.000 STOP LOSS READY (0) @ 4.384
⠧  2:57:22   ONTUSDT           qty:5.899 @ 4.41900000     pnl:0.000

the time、qty、price 、pnl will keep static after serveral minutes，the node terminal process will never connect to binance api interface...

**Comment by godisrko** [comment]
may be  i use a vpn connect,when the vpn disconnect,the bot will fronzen

**Comment by godisrko** [comment]
how offen does the bot request binance?

**Comment by jsappme** [comment]
all the time, it uses web sockets to listen to trades.

Yes if you lose the internet connection, the bots will stop receiving data and might get disconnected.

I will close this issue because it's not an issue with the bot but with your vpn internet connection.

**Comment by godisrko** [comment]
But when my internet is go on ,the bot can not work.

**Comment by jsappme** [comment]
show me the logs

**Comment by godisrko** [comment]
### Why are my websocket connections being dropped/disconnected?
### Every 3 minutes, active websocket connections will receive a ping. If you do not respond with a ### properly framed pong, your connection will be terminated.

this is binacne api support,when my internet is not good,the bot can't recive a ping,bot can not establish a new websocket,so the bot will frozen.
@jsappme how?

**Comment by jsappme** [comment]
Please copy and paste here what the bot is displaying.
