### ISSUE TITLE
async function without a catch block

### ISSUE THREAD

**Issue by godisrko** [jsappme/node-binance-trader#14]
⠼  2:08:33   NEOUSDT           qty:0.610 @ 39.66000000    pnl:0.000(node:37888) UnhandledPromiseRejectionWarning: Error: Order does not exist.
    at /Users/sky/Downloads/nbt3/node_modules/binance-api-node/dist/http.js:47:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:37888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jsappme** [comment]
issue gone with the new version
