### ISSUE TITLE
ERROR #7771 0.21917 :: Error: Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by sitan227** [jsappme/node-binance-trader#15]
ERROR #7771 0.21917 :: Error: Account has insufficient balance for requested action.

I have $130 and test with $100 but bot show this error.

**Comment by seevoid** [comment]
Same...

**Comment by jsappme** [comment]
This issue is caused by some trades that get partially filled or even previously filled so the amount is not accurate anymore. Aware of this one, and working on it to fix.

**Comment by FredMichel** [comment]
Any update on that one ? I read root cause could be related to fees management for each transaction. Does it make sense?

**Comment by BenStuart** [comment]
+1 the fee management idea.

Seems like it tried to sell 19.53 XX. "ERROR #7771 19.53000 :: Error: Account has insufficient balance for requested action." when I had 19.51000 XX in my wallet, which would be minus the transaction fee.

**Comment by BenStuart** [comment]
The system is expecting you to use BNB for the transactions so the amount never changes when selling off. If you don't want to use BNB for your transactions. You can code in the 0.1% transaction fee to the sells i.e Math.floor(buy_amount - (buy_amount * 0.001). But using BNB is probably better because you get 50% off the transaction fee atm.

**Comment by switecandy** [comment]
Insufficient balance even carrying out trade with BNB balance to pay fees.

What do I do to work?

![image](https://user-images.githubusercontent.com/42079143/46902137-2c647f00-ce96-11e8-98b4-6f006ce159e7.png)

**Comment by jsappme** [comment]
please make sure you own some BNB to pay for the fees. if you use BNB make sure you dont use the whole amount in your trade.

**Comment by switecandy** [comment]
![image](https://user-images.githubusercontent.com/42079143/46908433-00c6b080-cef9-11e8-8f93-463fea04fc27.png)

Error persists. About 19 USD in BNB, I put 16 USD to be used. I am using a BNB currency for.

**Comment by switecandy** [comment]
Error persists. About 19 USD in BNB, I put 16 USD to be used. I am using a BNB currency for.

![image](https://user-images.githubusercontent.com/42079143/46908462-703ca000-cef9-11e8-931d-f429c6ebb83d.png)

**Comment by switecandy** [comment]
Error persists. About 19 USD in BNB, I put 16 USD to be used. I'm using a BNB currency to trade.

![image](https://user-images.githubusercontent.com/42079143/46908528-6e271100-cefa-11e8-8209-df5a0be84d70.png)

**Comment by switecandy** [comment]
Error persists. About 19 USD in BNB, I put 16 USD to be used. I'm using BNB to trade. Being, more than 15 USD for the trade and enough for rates.

![image](https://user-images.githubusercontent.com/42079143/46908534-a2023680-cefa-11e8-9ad8-5f941e5fe86d.png)

**Comment by switecandy** [comment]
Or does it have a minimum value for the trade and the rate? How much do I have to have minimum balance of BNB and BTC, for example?

**Comment by jsappme** [comment]
I will review this issue and make some code changes next week.

**Comment by switecandy** [comment]
Is there a minimum value of BTC and BNB for example?

**Comment by switecandy** [comment]
> Acho que encontrei a causa raiz: você tem que comprar BNB suficiente para pagar as taxas!

Do you know how much BNB I need to have exactly?

**Comment by jsappme** [comment]
enough to pay for the fees.

**Comment by switecandy** [comment]
So the robot is in trouble. I left enough balance in BNB, tested trade with BTC leaving BNB for rates and tested trade with BNB without using the whole balance, leaving a little for rates and even then it did not work. Always says insufficient balance. If it works the sooner I'll send you cryptmoedas.

**Comment by jsappme** [comment]
no the robot is not in trouble, it is working fine on my side.

![screen shot 2018-10-14 at 10 55 30 am](https://user-images.githubusercontent.com/13439477/46919663-cf54f000-cf9f-11e8-9954-01b0e24094a8.png)

Please make sure you have some extra BNB on your balance to pay for the fees.

**Comment by jsappme** [comment]
how much BNB are leaving on the table each time?

**Comment by switecandy** [comment]
What does USD 1.2 mean in the second line?

Approximately 8 USD BNB for fee and I used 16 USD of BNB for the trade.

**Comment by switecandy** [comment]
To perform this photo test, when did you have BNB? How much do you have to BNB total, how many USD did you use and how much did you leave for fees?

**Comment by switecandy** [comment]
![image](https://user-images.githubusercontent.com/42079143/46931638-4b375280-d009-11e8-98df-e8a65ea561fa.png)

Looks like it is contradictory, time he says insufficient balance, then says that I am 1000ms in advance. I try local time, universal time, correct the second, do not leave. What time do you use?

**Comment by switecandy** [comment]
I gotta get going, thanks, buddy. But one thing, mine was not like yours, gave an unexpected error, "0(node:1604) UnhandledPromiseRejectionWarning: Error: Order does not exist.
    at C:\Users\SonyVaio\Desktop\node-binance-trader-master\node_modules\binance-api-node\dist\http.js:47:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.", and now? How do you stay as your example?

![image](https://user-images.githubusercontent.com/42079143/46932480-38268180-d00d-11e8-93b7-96caa94bd6d1.png)

**Comment by switecandy** [comment]
Friend, good news, I got the robot to work. But it gave a different error than yours when starting the trade, the robot bought the TRX, but it gave a strange error, as in the photo below. What will that be?

![image](https://user-images.githubusercontent.com/42079143/46932622-c8fd5d00-d00d-11e8-9dd8-842a75d14d9a.png)

**Comment by switecandy** [comment]
![image](https://user-images.githubusercontent.com/42079143/46932762-6193dd00-d00e-11e8-81aa-5ce945762669.png)

I did it with different currency and it also made strange mistakes, different from your example that you tested today.
