### ISSUE TITLE
Trailing Stop Loss

### ISSUE THREAD

**Issue by scratchmaster2** [jsappme/node-binance-trader#17]
When using the trailing stop loss the bot sets a Stop-Limit Ask rather than just a Limit. Therefore the Stop is set at the percentage requested but the actual limit is set at a level not specified by the user.

For E.g when I used a trailing stop loss, I set 1% as the trailing stop loss, for my first test the Stop was at 1% but the limit 5% so I ended up losing a lot more than anticipated!

**Comment by jsappme** [comment]
yes in order to give the maximum executable probabilities, I set a lower loss price. You can edit this value to what you want. this is not a real issue so I will close this issue for now.
