### ISSUE TITLE
Insufficient balance HELP

### ISSUE THREAD

**Issue by switecandy** [jsappme/node-binance-trader#22]
![image](https://user-images.githubusercontent.com/42079143/46902026-3dac8c00-ce94-11e8-88d4-3f7cfc40cbb3.png)

Insufficient balance even carrying out trade with BNB balance to pay fees.

What do I do to work?

**Comment by zywx** [comment]
Same problem here didn’t find any solution yet

**Comment by jsappme** [comment]
please make sure you own some BNB to pay for the fees.
