### ISSUE TITLE
ERRROR #1233 - Error: Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by hiddenlucas** [jsappme/node-binance-trader#24]
Hello, I get very often this error. Maybe possible is set a little delay before set stop loss? or it's other kind problem?
 
⠏  3:33:42    RVNBTC        qty:3986.000 @ 0.00000810     pnl:0.000 INITAL BUY ORDER FULLY EXECUTED 
⠸  3:33:42    RVNBTC        qty:1746.000 @ 0.00000808    pnl:-0.737 FINAL BUY PRICE @ 0.0000081
⠇  3:33:42    RVNBTC        qty:1746.000 @ 0.00000808    pnl:-0.737 ERRROR #1233 STOP PRICE (0.00000802) Error: Account has insufficient balance for requested action.

**Comment by exit490** [comment]
I had the same problem. You need to lower the transaction fee. For sale to be executed with the correct value.

```
  9:46:05    MTLBTC          qty:43.470 @ 0.00007700     pnl:0.000 BUY ORDER NOT YET FULLY EXECUTED 
⠸  9:46:07    MTLBTC          qty:16.420 @ 0.00007700     pnl:0.000 BUY ORDER NOT YET FULLY EXECUTED 
⠹  9:49:02    MTLBTC         qty:215.660 @ 0.00007690     pnl:0.000 INITAL BUY ORDER FULLY EXECUTED 
⠦  9:49:02    MTLBTC         qty:215.660 @ 0.00007690     pnl:0.000 FINAL BUY PRICE @ 0.0000769
⠙  9:49:02    MTLBTC         qty:215.660 @ 0.00007690     pnl:0.000 ERRROR #1233 STOP PRICE (0.0000763) Error: Account has insufficient balance for requested action.
 SELLING AT MARKET PRICE 
✖  ERROR #7771 1196.36 :: Error: Account has insufficient balance for requested action.
```

**Comment by sahni619** [comment]
Even i get this issue and the app hangs with asset stuck in order.
<img width="1088" alt="Screen Shot 2019-03-23 at 8 27 42 PM" src="https://user-images.githubusercontent.com/17097887/54867808-9f114900-4daa-11e9-87d5-dc5d06565aeb.png">

**Comment by jsappme** [comment]
issue gone with the new version
