### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by afmsavage** [jsappme/node-binance-trader#25]
Receiving the following when trying to run the trader.  

`? Enter the Trailing Loss Percentage: 1
? Start the trade now? Yes
(node:14223) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at start_trading (/home/tony/dev/node-binance-trader/index.js:319:28)
    at inquirer.prompt.then.answers (/home/tony/dev/node-binance-trader/index.js:309:7)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:14223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by ChristianPresley** [comment]
I am also receiving the same error on node v10

**Comment by johnmerced** [comment]
Same issue.

**Comment by switecandy** [comment]
Solution?

**Comment by jsappme** [comment]
issue gone with the new version
