### ISSUE TITLE
 Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by narcdrafics** [jsappme/node-binance-trader#26]
(node:7419) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at start_trading (/home/tony/node-binance-trader/index.js:319:28)
    at inquirer.prompt.then.answers (/home/tony/node-binance-trader/index.js:309:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:7419) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7419) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by afmsavage** [comment]
Looks like this is due to the API change that Binance implemented.

Changes can be found here.  This was the day it broke.  
https://github.com/binance-exchange/binance-official-api-docs/commit/a16e3d84e2e78c9fa1de0083f8e0eb966c726448

**Comment by nillo** [comment]
made a quick fix for this: https://github.com/jsappme/node-binance-trader/pull/27/files

**Comment by sagar-srivastava** [comment]
I confirm, I get the same error, wish you get time to work on it. Thanks

**Comment by Jman1** [comment]
I'm getting the same error

**Comment by jeffbarreto** [comment]
it seems that they moved the information to the index 2 line 136

_.filter (results.symbols, {symbol: pair}) [0] .filters [2] .stepSize

as I do not know the background api would like a confirmation
