### ISSUE TITLE
Errors noticed

### ISSUE THREAD

**Issue by switecandy** [jsappme/node-binance-trader#31]
I noticed that besides the error to execute, it is also giving error in the command npm i -g

![image](https://user-images.githubusercontent.com/42079143/54468791-31906780-476f-11e9-9a29-d75d32ae578e.png)

![image](https://user-images.githubusercontent.com/42079143/54468807-51c02680-476f-11e9-9c21-bbfe7ca982be.png)

Does anyone have a solution?

**Comment by tezeug** [comment]
I get the same error.

**Comment by tezeug** [comment]
Fixed.

**Comment by jsappme** [comment]
issue fixed with the latest commit
