### ISSUE TITLE
Undefined error on trader

### ISSUE THREAD

**Issue by aolin480** [jsappme/node-binance-trader#36]
I am currently getting the following error when the trader receives input from the socket from the server. I just pulled the repo yesterday too. I saw someone had the same issue, and that it was fixed in a new version but still happening on `master`

```
> node-binance-trader@0.1.1 trader /Users/xxx/crypto/node-binance-trader
> node trader.js

NBT trader running.
Trader connected.
=> BUY SIGNAL BNBBTC undefined
(node:38523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'padStart' of undefined
    at Socket.<anonymous> (/Users/xxx/crypto/node-binance-trader/trader.js:46:32)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:38523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38523) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by jsappme** [comment]
Hi @aolin480, thank you very much for reporting this issue. I just pushed a new commit of the trader that should fix this issue. It still does not auto trade for real (no binance keys needed) but it will paper trade the signals from the strategies you select at [Bitcoin vs. Altcoins](https://bitcoinvsaltcoins.com/) You will need to copy your BvA key (that you get after signing up) to trader.js. This is a work in progress, there might be some bugs. I am adding new features on the daily basis. Let me know how it goes.

**Comment by aolin480** [comment]
Awesome! Thanks! Just pulled, and will check it out. Just wanted to see how this all works, and getting those errors were throwing me off. lol I'll dig into the code as well, and see what I can do with the data. I appreciate all of this!
