### ISSUE TITLE
Got error with Telegram when running trader mode

### ISSUE THREAD

**Issue by theblackvn** [jsappme/node-binance-trader#46]
I set token and chat_id for telegram.
When run trader mode, the error message was as below

> my-pc:node-binance-trader-master user$ npm run trader

node-binance-trader@0.2.3 trader folder/node-binance-trader-master
node trader.js

[bot.plugin] loaded 'regExpMessage' plugin
[bot.plugin] loaded 'shortReply' plugin
[bot.plugin] loaded 'askUser' plugin
folder/node-binance-trader-master/trader.js:729
telBot.on('/info', async (msg) => {       
^

ReferenceError: telBot is not defined
    at Object.<anonymous> (/folder/node-binance-trader-master/trader.js:729:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-binance-trader@0.2.3 trader: `node trader.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-binance-trader@0.2.3 trader script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jsappme** [comment]
@Plasto13 any idea on this issue?

**Comment by prenesh0309** [comment]
looking to set up alerts on telegram. any solution to this?

**Comment by Plasto13** [comment]
I'm just very busy.  I'll try next week

**Comment by bruvv** [comment]
This is still an issue and @Plasto13 your solution means I have to fill in my binance keys. altough the current version doesn't need this. For testing this feels much saver for me to not fill out my api

**Comment by jsappme** [comment]
TG keeps creating bugs. I disabled this feature for now until it gets more stable.
