### ISSUE TITLE
Trades not considering fees

### ISSUE THREAD

**Issue by EnriqueSampaio** [jsappme/node-binance-trader#51]
Hi, first of all, amazing tool!

I'm exploring node-binance-trader with BvA, and I'm seeing that the trades doesn't consider fees, so it tries to sell the same amount of coins it has bought, causing insufficient funds error in Binance.

I'm using the "BVA3H+ ALTS" strategy and deployed the trader to Heroku from https://github.com/jsappme/nbt-binance-auto-trader project.

Am I missing something?
Thank you

**Comment by jsappme** [comment]
yes you always need to have some BNB on your wallet(s) to pay for the fees.
