### ISSUE TITLE
[ERROR] Issue processing the Market Buy Order

### ISSUE THREAD

**Issue by leovarmak** [jsappme/node-binance-trader#6]
Hey man !
I setup everything the right way and I verified I have enough funds but I get this error. 

<img width="784" alt="nbt-error" src="https://user-images.githubusercontent.com/14135553/41507766-275a7050-7257-11e8-96fe-8259f305caee.png">

What might be wrong ?

**Comment by jsappme** [comment]
The minimum amount should be more than 10 usd of value.

**Comment by leovarmak** [comment]
@jsappme Why is that so ? Binance lets me put orders less than 10 USD

**Comment by jsappme** [comment]
Even limit order?

**Comment by leovarmak** [comment]
No. I don't think so.
But since we are placing a market order anyway can we do so thing so that that error doesn't popup ?

**Comment by jsappme** [comment]
the bot will first try to buy at a better price than the market price.
