### ISSUE TITLE
Question: why use `node-binance-api` and `binance-api-node` 

### ISSUE THREAD

**Issue by JoeSchr** [jsappme/node-binance-trader#60]
hi, first of all, great project. 

I hope you are not reading this and instead are celebrating your 600%+ gains on the bahamas.

Should you still be reading this, I have a question:
 Why do you use 2 different libraries for accessing binance?

Also I published a PR for a crash that occured on my system
Thanks

**Comment by dargmuesli** [comment]
I just merged the PR you mentioned :)

@jsappme could you answer Joe's question?

**Comment by jsappme** [comment]
> Why do you use 2 different libraries for accessing binance?

At the time of dev of this script, I could not do everything that I wanted with onle one of those pkges.
