### ISSUE TITLE
Profit/Loss stats are not correct

### ISSUE THREAD

**Issue by ronnyandre** [jsappme/node-binance-trader#69]
I had issues with the API key settings in Binance, which meant that the trader couldn't communicate with Binance API. However, I was able to manually close a trade and now it shows 0.444% profit for that trade, while the API wasn't working. How can I manually correct these stats?

**Comment by dargmuesli** [comment]
That's currently not possible, but the next feature on @jsappme's roadmap.

**Comment by dargmuesli** [comment]
Please open this issue at https://github.com/jsappme/BitcoinVsAltcoins/
It's a new project dedicated to issues regarding the website, so this repository can be kept to technical issues with the trader itself.
Thank you!
