### ISSUE TITLE
Express usage on trader.js

### ISSUE THREAD

**Issue by mtxr** [jsappme/node-binance-trader#73]
Hey guys, I do have a question about the express usage on trader.js.

Does anyone know why we just listen to a port and serve empty string to the address?

**Comment by jsappme** [comment]
no special reason

**Comment by mtxr** [comment]
Cool, i'm writing the tests as requested in the other PR I've filed, is it ok to remove express from the trader code? So I don't need to test it there as well

**Comment by jsappme** [comment]
yes I think it's okay

**Comment by dargmuesli** [comment]
Well, isn't the reason for having express serve an empty page that Heroku users are able to set an uptime robot up for their trder instance?

**Comment by olvisdevalencia** [comment]
I think the reason if for ping the bot from another watcher or the uptimerobot to get the heroku's app up (when using it on free dyno).
