### ISSUE TITLE
MongoDB on Heroku

### ISSUE THREAD

**Issue by dederaditya** [jsappme/node-binance-trader#79]
Hello there,

I'm here to tell my issues to run the script on Heroku. I'm using @iyenal version of script(autobalance), and it does need mongodb to work. In this case it stores the data to Atlas cloud not to a local mongodb.

I think there's an issue caused by package-lock.json, so the error was _xxx_ module is not found, even after you inserted that module you will somehow stuck at module named b1, I deleted package-lock.json to solve this issue.
You can check my error logs, before deleting package-lock.json
[error (2).txt](https://github.com/jsappme/node-binance-trader/files/6054556/error.2.txt)

I edited package.json to this,
[https://gist.github.com/dederaditya/86c55a55e25fbcac0a975091acce4a80](url)

I think this version of package.json only support trader function? Because original package.json has `"main": "./src/server.js"`

**Comment by dargmuesli** [comment]
Sorry, we cannot support bugs of forks in this issue tracker. Please direct your thoughts to iyenal unless the issue certainly comes from this repository.

**Comment by dederaditya** [comment]
herve told me to post this to issue section :/ nvm i fixed it anyway
