### ISSUE TITLE
INSTALL ON WINDOWS

### ISSUE THREAD

**Issue by newprogrammeram** [jsappme/node-binance-trader#82]
HI I HAVE WINDOWS 10
AND I DONT KNOW HOW TO INSTALL ON WINDOWS MAYBE HELP ME
FOR EXAMPLE 
WHATS EQUAL BELOW COMMAND IN WINDOWS?
cp .env.example .env

**Comment by dargmuesli** [comment]
Hey there, why are you writing all uppercase? Just a friendly notice: people might consider it screaming and would be less willing to help. Also, you can edit your message after it being sent.

Regarding your question: that's something to ask on Discord or on your favorite search engine. This issue tracker is for bug reports and feature requests. You can find that Discord linked in this project's README. Thank you for understanding!
