### ISSUE TITLE
Pairs in ENV

### ISSUE THREAD

**Issue by certifirm** [jsappme/node-binance-trader#95]
In trader, at this moment, the pair is hardcoded and margin_pairs variable too.  

I think that this 2 variables must be in .env file.  Because we must configure if we want use, for example, and USDT strategy like "ZEN", and the same for the pairs.

It's a suggestion.

**Comment by dargmuesli** [comment]
For margin pairs, those are already automatically loaded on the project's `testing` branch version. It would be great if you could help with testing by running this version yourself and report back to us if that works as expected.

**Comment by certifirm** [comment]
Nice.  I am testing the 0.4 branch two days ago, but poor activity in strategies.  I will use this one to test without problem.   I will report back.  Thanks for your work.

**Comment by certifirm** [comment]
For the moment all has worked well.  I am testing now the zen version with multiple pair (BTC and USDT)
