### ISSUE TITLE
Socket documentation

### ISSUE THREAD

**Issue by certifirm** [jsappme/node-binance-trader#96]
I am developing my own strategy and I had a lot of problems to connect with websockets.

I was using the version 4 of the socket.io-client.  Then I used 2.2 version when I look your package json.

I think that will be in the documentation, in the sockets section.

**Comment by dargmuesli** [comment]
What are you asking for? To include that version 2 is used on the documentation?
The testing branch already includes an upgrade to version 4, so that'll land in the release following 0.4.0.

**Comment by certifirm** [comment]
I only said that I don't use server.js to do my strategy and when I want to connect to BvA through socket,  I couldn't.  It may be interesting to put the version in the documentation, because I think that v4 is not compatible.
